apiVersion: 1

# Provision InfluxDB 2.x datasource using environment variables
# INFLUX_URL, INFLUX_ORG, INFLUX_TOKEN are passed to the Grafana container via docker-compose

datasources:
  - name: InfluxDB-crypto
    uid: influxdb-crypto
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: crypto-data
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      token: ${INFLUX_TOKEN}
